conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: /users/eleves-a/2022/jules.damidaux/Documents/Flower/MVA/compare_with_DPS/data/afhq_subset

measurement:
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0

  noise:
    name: gaussian
    sigma: 0.05
